CREATE DATABASE FINAL;

USE FINAL;

-- ========= STUDENT TABLE ===========
CREATE TABLE STUDENTS (
    STUDENTID INT PRIMARY KEY,
    FIRSTNAME VARCHAR(30),
    LASTNAME VARCHAR(30),
    EMAIL VARCHAR(50),
    ENROLLMENTDATE DATE
);

INSERT INTO STUDENTS VALUES
(1, 'JOHN', 'DOE', 'JOHN.DOE@GMAIL.COM', '2020-01-15'),
(2, 'EMMA', 'SMITH', 'EMMA.SMITH@GMAIL.COM', '2020-08-01'),
(3, 'RAHUL', 'SHARMA', 'RAHUL.SHARMA@GMAIL.COM', '2019-07-20'),
(4, 'PRIYA', 'PATEL', 'PRIYA.PATEL@GMAIL.COM', '2021-06-18'),
(5, 'AMIT', 'KUMAR', 'AMIT.KUMAR@GMAIL.COM', '2022-09-05'),
(6, 'AMAN', 'PATEL', 'AMAN.PATEL@GMAIL.COM', '2025-10-25');

-- ======== COURSE TABLE ==========
CREATE TABLE COURSES (
    COURSEID INT PRIMARY KEY,
    COURSENAME VARCHAR(50),
    DEPARTMENTID INT,
    CREDITS INT
);

INSERT INTO COURSES VALUES
(101, 'DATABASE SYSTEMS', 1, 4),
(102, 'DATA STRUCTURES', 1, 4),
(103, 'LINEAR ALGEBRA', 2, 3),
(104, 'ORGANIC CHEMISTRY', 4, 4),
(105, 'THERMODYNAMICS', 5, 3),
(106, 'WEB DESIGN', 6, 4);

-- ======== INSTRUCTOR TABLE ==========
CREATE TABLE INSTRUCTORS (
    INSTRUCTORID INT PRIMARY KEY,
    FIRSTNAME VARCHAR(30),
    LASTNAME VARCHAR(30),
    EMAIL VARCHAR(50),
    DEPARTMENTID INT
);

INSERT INTO INSTRUCTORS VALUES
(1, 'ALICE', 'BROWN', 'ALICE.BROWN@GMAIL.COM', 1),
(2, 'BOB', 'LEE', 'BOB.LEE@GMAIL.COM', 2),
(3, 'CHARLES', 'DAVIS', 'CHARLES.DAVIS@GMAIL.COM', 3),
(4, 'DIYA', 'MEHTA', 'DIYA.MEHTA@GMAIL.COM', 4),
(5, 'RAJ', 'VERMA', 'RAJ.VERMA@GMAIL.COM', 5),
(6, 'MANAN', 'JOSHI', 'MANAN.JOSHI@GMAIL.COM', 6);

-- ========== ENROLLMENTS TABLE ===========
CREATE TABLE ENROLLMENTS (
    ENROLLMENTID INT PRIMARY KEY,
    STUDENTID INT,
    COURSEID INT,
    ENROLLMENTDATE DATE,
    FOREIGN KEY (STUDENTID) REFERENCES STUDENTS(STUDENTID),
    FOREIGN KEY (COURSEID) REFERENCES COURSES(COURSEID)
);

INSERT INTO ENROLLMENTS VALUES
(1, 1, 101, '2024-08-05'),
(2, 2, 102, '2020-08-06'),
(3, 3, 103, '2013-07-25'),
(4, 4, 104, '2021-06-20'),
(5, 5, 105, '2022-09-10'),
(6, 6, 106, '2023-10-25');

-- ========= DEPARTMENT TABLE ==========
CREATE TABLE DEPARTMENTS (
    DEPARTMENTID INT PRIMARY KEY,
    DEPARTMENTNAME VARCHAR(50)
);

INSERT INTO DEPARTMENTS VALUES
(1, 'COMPUTER SCIENCE'),
(2, 'MATHEMATICS'),
(3, 'PHYSICS'),
(4, 'CHEMISTRY'),
(5, 'MECHANICAL'),
(6, 'STASTICS');

-- 1. CRUD

-- === READ ===
SELECT * FROM STUDENTS;

SELECT * FROM COURSES;

SELECT * FROM INSTRUCTORS;

SELECT * FROM ENROLLMENTS;

SELECT * FROM DEPARTMENTS;

-- === UPDATE ===
UPDATE STUDENTS
SET FIRSTNAME = 'PRATIK'
WHERE STUDENTID = 2;

UPDATE COURSES
SET COURSENAME = 'VIDEO EDITING'
WHERE COURSEID = 103;

UPDATE INSTRUCTORS
SET EMAIL = 'diya.mehta5@gmail.com'
WHERE INSTRUCTORID = 4;

UPDATE DEPARTMENTS
SET DEPARTMENTNAME = 'BIOLOGY'
WHERE DEPARTMENTID = 3;

-- === DELETE ===
DELETE FROM STUDENTS WHERE STUDENTID = 6;

DELETE FROM COURSES WHERE COURSEID = 106;

DELETE FROM INSTRUCTORS WHERE INSTRUCTORID = 6;

DELETE FROM ENROLLMENTS WHERE ENROLLMENTID = 6;

DELETE FROM DEPARTMENTS WHERE DEPARTMENTID = 6;

-- 2. Retrieve students who enrolled after 2022:
SELECT * FROM STUDENTS 
WHERE ENROLLMENTDATE > '2022-12-31';

-- 3. Retrieve courses offered by the Mathematics department with a limit of 5:
SELECT C.* FROM COURSES C
JOIN DEPARTMENTS D ON C.DEPARTMENTID = D.DEPARTMENTID
WHERE D.DEPARTMENTNAME = 'MATHEMATICS'
LIMIT 5;

-- 4. Number of students enrolled in each course (filter for courses with > 5 students):
SELECT COURSEID, COUNT(STUDENTID) AS StudentCount
FROM ENROLLMENTS
GROUP BY COURSEID
HAVING COUNT(STUDENTID) > 5;

-- 7. Calculate the average number of credits for all courses:
SELECT AVG(CREDITS) AS AverageCredits FROM COURSES;

-- 8. Find the maximum salary of instructors in the Computer Science departmenT
SELECT MAX('SALARY') FROM INSTRUCTORS I
JOIN DEPARTMENTS D ON I.DEPARTMENTID = D.DEPARTMENTID -- this column does not exist bcz salary is not in my table
WHERE D.DEPARTMENTNAME = 'COMPUTER SCIENCE';

-- 9. Count the number of students enrolled in each department.
SELECT D.DEPARTMENTNAME, COUNT(S.STUDENTID) AS TotalStudents
FROM DEPARTMENTS D
LEFT JOIN STUDENTS S ON D.DEPARTMENTID = S.STUDENTID
GROUP BY D.DEPARTMENTNAME;

-- 10. INNER JOIN: Retrieve students and their corresponding courses:
SELECT S.FIRSTNAME, S.LASTNAME, C.COURSENAME
FROM STUDENTS S
INNER JOIN ENROLLMENTS E ON S.STUDENTID = E.STUDENTID
INNER JOIN COURSES C ON E.COURSEID = C.COURSEID;

-- 11. LEFT JOIN: Retrieve all students and their corresponding courses (if any):
SELECT S.FIRSTNAME, S.LASTNAME, C.COURSENAME
FROM STUDENTS S
LEFT JOIN ENROLLMENTS E ON S.STUDENTID = E.STUDENTID
LEFT JOIN COURSES C ON E.COURSEID = C.COURSEID;

-- 12. Subquery: Find students enrolled in courses that have more than 10 students:
SELECT * FROM STUDENTS 
WHERE STUDENTID IN (
    SELECT STUDENTID FROM ENROLLMENTS 
    WHERE COURSEID IN (
        SELECT COURSEID FROM ENROLLMENTS 
        GROUP BY COURSEID 
        HAVING COUNT(STUDENTID) > 10
    )
);

-- 13. Extract the year from the EnrollmentDate of students:
SELECT FIRSTNAME, LASTNAME, YEAR(ENROLLMENTDATE) AS EnrollmentYear 
FROM STUDENTS;

-- 14. Concatenate the instructor's first and last name:
SELECT CONCAT(FIRSTNAME, ' ', LASTNAME) AS InstructorFullName 
FROM INSTRUCTORS;

-- 15. Calculate the running total of students enrolled in courses:
SELECT ENROLLMENTDATE, 
       COUNT(STUDENTID) OVER (ORDER BY ENROLLMENTDATE) AS RunningTotal
FROM ENROLLMENTS;

-- 16. Label students as 'Senior' or 'Junior' based on enrollment (> 4 years = Senior):
SELECT FIRSTNAME, LASTNAME, ENROLLMENTDATE,
       CASE 
           WHEN DATEDIFF(CURRENT_DATE, ENROLLMENTDATE) / 365 > 4 THEN 'Senior'
           ELSE 'Junior'
       END AS StudentStatus
FROM STUDENTS;