CREATE DATABASE PROJECT1;

USE PROJECT1;

CREATE TABLE CUSTOMERS(
    CUSTOMERID INT PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL VARCHAR(30),
    ADDRESS VARCHAR(50)
);

INSERT INTO CUSTOMERS(CUSTOMERID, NAME, EMAIL, ADDRESS)
VALUES
(1, 'Alice', 'alice53@gmail.com', 'Ahemdabad'),
(2, 'Bob', 'bob47@gmail.com', 'Mumbai'),
(3, 'Charlie', 'charl22@gmail.com', 'Pune'),
(4, 'Emma', 'emma01@gmail.com', 'Delhi'),
(5, 'Devid', 'devid33@gmail.com', 'Ahemdabad');

-- RETRIEVE ALL CUSTOMER DETAILS
SELECT * FROM CUSTOMERS;

-- UPDATE CUSTOMER ADDRESS
UPDATE CUSTOMERS
SET ADDRESS = 'bob56@gmail.com'
WHERE CUSTOMERID = 2;

-- DELETE A CUSTOMER USING THEIR CUSTOMERID
DELETE FROM CUSTOMERS WHERE CUSTOMERID = 5;

-- DISPLAY ALL CUSTOMERS WHOSE NAME IS ALICE
SELECT * FROM CUSTOMERS 
WHERE NAME = 'ALICE';

-- ====== OREDER TABLE =======
CREATE TABLE ORDERS(
    ORDERID INT PRIMARY KEY,
    CUSTID INT,
    ORDERDATE DATE,
    TOTALAMOUNT INT,
    FOREIGN KEY (CUSTID) REFERENCES CUSTOMERS(CUSTOMERID)
);

-- INSERT AT LEAST 5 SAMPLE ORDERS INTO THE ORDERS TABLE
INSERT INTO ORDERS VALUES
(21, 1, '2025-11-12', 5000),
(22, 4, '2025-10-02', 2000),
(23, 3, '2025-07-18', 900),
(24, 2, '2025-12-21', 500),
(25, 1, '2025-05-05', 1000);

SELECT * FROM ORDERS;

-- RETRIEVE ALL ORDERS MADE BY A SPECIFIC NUMBERS
SELECT * FROM ORDERS WHERE CUSTID = 1;

-- UPDATE AN ORDER'S TOTAL AMOUNT
UPDATE ORDERS
SET TOTALAMOUNT = 4000
WHERE CUSTID = 3;

-- DELETE AN ORDERS USING ORDERID
DELETE FROM ORDERS WHERE ORDERID = 22;

-- RETRIEVE ORDER PLACED INTHE LAST 30 DAYS
SELECT * FROM ORDERS 
WHERE ORDERDATE >= CURRENT_DATE - INTERVAL 30 DAY;

-- HIGEST ORDER AMOUNT
SELECT MAX(TOTALAMOUNT) FROM ORDERS;

-- LOWEST ORDER AMOUNT
SELECT MIN(TOTALAMOUNT) FROM ORDERS;

-- AVRAGE ORDER AMOUNT
SELECT AVG(TOTALAMOUNT) FROM ORDERS;

-- ======= PRODUCT TABLE ========
CREATE TABLE PRODUCTS(
    PRODUCTID INT PRIMARY KEY,
    PRODUCTNAME VARCHAR(100),
    PRICE INT,
    STOCK INT 
);

INSERT INTO PRODUCTS VALUES
(31, 'SUGAR', 500, 25),
(32, 'TEA', 300, 20),
(33, 'SALT', 100, 10),
(34, 'CHIILI', 700, 35),
(35, 'OIL', 600, 80);

SELECT * FROM PRODUCTS;

-- ALL PRODUCTS SORTED BY PRICE IN DECENDING ORDERS
SELECT * FROM PRODUCTS ORDER BY PRICE DESC;

-- UPDATE A PRICE OF A SPECIFIC ORDERS
UPDATE PRODUCTS
SET PRICE = 200
WHERE PRODUCTID = 33;

-- DELETE A PRODUCTSIF IT'S OUT OF STOCK
DELETE FROM PRODUCTS WHERE PRODUCTID = 50;

-- RETRIEVE PRODUCTS WHOSE PRICE BETWEEN 500 AND 2000
SELECT * FROM PRODUCTS WHERE PRICE BETWEEN 500 AND 2000;

-- HIGHEST PRICE
SELECT MAX(PRICE) FROM PRODUCTS;

-- LOWEST PRICE
SELECT MIN(PRICE) FROM PRODUCTS;

-- ====== ORDER DETAILS TABLE =======
CREATE TABLE ORDERDETAILS(
   ORDERDETAILID INT PRIMARY KEY,
   ORID INT,
   PRID INT,
   QUANTITY INT,
   SUBTOTAL INT
);

INSERT INTO ORDERDETAILS VALUES
(41, 21, 32, 1, 50000),
(42, 24, 31, 2, 40000),
(43, 23, 34, 3, 60000),
(44, 24, 33, 4, 10000),
(45, 25, 35, 3, 80000);

SELECT * FROM ORDERDETAILS;

-- RETRIEVE ALL ORDER DETAILS FOR A SPECIFIC ORDER
SELECT * FROM ORDERDETAILS WHERE ORDERDETAILID = 42;

-- CALCULATE THE TOTAL REVANUE GENERATED FROM ALL ORDERS USING SUM()
SELECT SUM(SUBTOTAL) FROM ORDERDETAILS;

-- Top 3 most ordered products
SELECT PRID, SUM(QUANTITY) 
FROM ORDERDETAILS
GROUP BY PRID
ORDER BY SUM(QUANTITY) DESC 
LIMIT 3;

-- COUNT 
SELECT PRID, COUNT(*) AS times_sold
FROM ORDERDETAILS
WHERE PRID = 24
GROUP BY PRID;
