CREATE DATABASE DATADIGGER;

USE DATADIGGER;

CREATE TABLE Customers(
    customerID INT PRIMARY KEY,
    NAME VARCHAR(100),
    Email varchar(100),
    Address varchar(100),
    foreign key (customerID) references Customers(custID)
);

INSERT INTO Customers(customerID, NAME, Email, Address)
VALUES
(1, 'Alice', 'alice53@gmail.com', 'Ahemdabad'),
(2, 'Bob', 'bob47@gmail.com', 'Mumbai'),
(3, 'Charlie', 'charl22@gmail.com', 'Pune'),
(4, 'Emma', 'emma01@gmail.com', 'Delhi'),
(5, 'Devid', 'devid33@gmail.com', 'Ahemdabad');

-- RETRIEVE ALL CUSTOMER DETAILS
SELECT * FROM Customers;

-- UPDATE CUSTOMERS ADDRESS
UPDATE Customers
SET Address = Surat
WHERE customerID = 1;

-- DISPLAY ALL CUSTOMERS WHOSE NAME ALICE
SELECT * FROM Customers
WHERE NAME = Alice;


-- ====== OREDER TABLE =======

CREATE TABLE ORDERS(
   orderID INT PRIMARY KEY,
   custID INT,
   OrderDate date,
   TotalAmount INT,
   FOREIGN KEY (orderID) references ORDERS(ORID)
);

-- INSERT AT LEAST 5 SAMPLE ORDERS INTO THE ORDERS TABLE
INSERT INTO ORDERS VALUES
(201, 1, '2025-11-12', 5000),
(202, 4, '2025-10-02', 2000),
(203, 3, '2025-07-18', 900),
(204, 2, '2025-12-21', 500),
(205, 5, '2025-05-05', 1000);

-- RETRIEVE ALL ORDERS MADE BY A SPECIFIC NUMBERS
SELECT * FROM  ORDERS WHERE customerID = 3;

-- UPDATE ALL ORDER'S TOTAL AMOUNT
UPDATE Customers
SET TotalAmount = 4500
WHERE orderID = 203;

-- DELETE AN ORDER'S USING ITS ORDERID
DELETE FROM ORDERS WHERE orderID = 2;

-- RETRIEVE ORDER PLACED INTHE LAST 30 DAYS
SELECT * FROM ORDERS 
WHERE OrderDate >= CURENT_DATE - INTERVAL 30 DAY;

-- HIGEST ORDER AMOUNT
SELECT MAX(TotalAmount) FROM ORDERS;

-- LOWEST ORDER AMOUNT
SELECT MIN(TotalAmount) FROM ORDERS;

-- AVRAGE ORDER AMOUNT
SELECT AVG(TotalAmount) FROM ORDERS;


-- ======= PRODUCT TABLE ========
CREATE TABLE PRODUCTS(
    ProductID INT PRIMARY KEY,
    ProductName VARCHAR(100),
    PRICE INT,
    STOCK INT,
    FOREIGN KEY(ProductID) REFERENCES PRODUCTS(PRID)
);

INSERT INTO PRODUCTS VALUES
(301, 'SUGAR', 500, 25),
(302, 'TEA', 300, 20),
(303, 'SALT', 100, 10),
(304, 'CHIILI', 700, 35),
(305, 'OIL', 600, 80);

SELECT * FROM PRODUCTS;
 
-- ALL PRODUCTS SORTED BY PRICE IN DECENDING ORDERS
SELECT * FROM PRODUCTS ORDER BY PRICE DESC;

-- UPDATE THE PRICE OF A SPECIFIC PRODUCT
UPDATE PRODUCTS
SET PRICE = 900
WHERE ProductID = 5;

-- DELETE A PRODUCTSIF IT;S OUT OF STOCK
DELETE FROM Products WHERE Stock=0;

-- RETRIEVE PRODUCTS WHOSE PRICE BETWEEN 500 AND 2000
SELECT * FROM PRODUCTS WHERE PRICE BETWEEN 500 AND 2000;

-- HIGHEST PRICE
SELECT MAX(PRICE) FROM PRODUCTS;

-- LOWEST PRICE
SELECT MIN(PRICE) FROM PRODUCTS;


-- ====== ORDER DETAILS TABLE =======
CREATE TABLE ORDERDETAILS(
   ORDERDETAILID INT PRIMARY KEY,
   ORID INT,
   PRID INT,
   QUANTITY INT,
   SUBTOTAL INT
);

INSERT INTO ORDERDETAILS VALUES
(1, 201, 302, 1, 50000),
(2, 202, 301, 2, 40000),
(3, 203, 304, 3, 60000),
(4, 204, 303, 4, 10000),
(5, 205, 305, 5, 80000);

SELECT * FROM ORDERDETAILS WHERE ORID = 1;

SELECT SUM(SUBTOTAL) FROM ORDERDETAILS;

-- Top 3 most ordered products
SELECT ProductID, SUM(QUANTITY) 
FROM ORDERDETAILS
GROUP BY ProductID 
ORDER BY SUM(QUANTITY) DESC 
LIMIT 3;

-- 
SELECT COUNT(ProductID)
FROM ORDERDETAILS
WHERE ProductID = 1;
