CREATE database sql4;

use sql4;


CREATE TABLE STUDENTS(
     ID INT PRIMARY KEY,
     NAME VARCHAR(100),
     AGE INT,
     PERCENTAGE DECIMAL(10,2)
);



INSERT INTO STUDENTS(ID, NAME, AGE, PERCENTAGE)
VALUES(1, 'SHIVI', 18, 95.27);



INSERT INTO STUDENTS(ID, NAME, AGE, PERCENTAGE)
VALUES
(2, 'VISHU', '17', 96.55),
(3, 'KRISH', 19, 89.88),
(4, 'SRUSHTI', 18, 78.16),
(5, 'MANAV', 19, 98.79),
(6, 'KHUSHI', 20, 88.23);

SELECT * FROM STUDENTS;

-- SELECT SPECIFIC COLUMNS
SELECT NAME, AGE FROM STUDENTS;

-- FILTER RECORDS USING WHERE CLOUS
SELECT * FROM STUDENTS WHERE PERCENTAGE > 88.23;

-- UPDATE PR SPECIFIC STUDENTS
UPDATE STUDENTS
SET PERCENTAGE = 99.99
WHERE ID = 1;

-- DELETE SPECIFIC RECORDS
DELETE FROM STUDENTS WHERE ID = 1;